### ISSUE TITLE
Need more examples

### ISSUE THREAD

**Issue by JIBIN-P** [deinstapel/verdaccio-groupnames#2]
I am currently using verdaccio with htpasswd as the auth plugin and all username and password are stored in the htpasswd file.
My question is how can I use groupnames feature to distinguish between two types of users  npmUsers and npmAdmin based on htpasswd auth.
I couldn't understand the examples in the readme.md like what does $group refer to and which users come under fancyCompany-owner and fancyCompany-employee.
It would be very helful of you to point me in the right direction.

**Comment by martin31821** [comment]
Basically, verdaccio knows authentication plugins (= Plugins, that lookup usernames and groups, like LDAP or hdpasswd) and authorization plugins (= plugins, that use the username and groups to grant access/publish/unpublish to users) 

This plugin simplifies the configuration of scoped packages, it allows the access to a package if the package scope matches **any** group assigned to the requesting user.

**Comment by JIBIN-P** [comment]
It would very helpful if you could give me an example on how to add users to a group and then assign those groups to access and publish for those group of users.
I only know the $all and $authenticated groups for htpasswd which is the default auth for verdaccio I would love to know how this auth works with a good example if I understand it well enough then I will document those understanding so that others will find it easier to use this.

**Comment by martin31821** [comment]
I don't know how to add groups using the htpasswd plugin, sorry.
We are using our ldap plugin in our deployment which crawls groups based on an LDAP query.
Our config looks like this:
```yaml
  storage: /verdaccio/storage/data
  max_body_size: 100mb
  uplinks:
    npmjs:
      url: https://registry.npmjs.org/
  packages:
    '@*/*':
      access: '$group'
      publish: '$group'
      proxy: npmjs
    '**':
      access: '$authenticated'
      publish: '$authenticated'
      proxy: npmjs
  logs:
    - type: stdout
      format: pretty
      level: info
  store:
    aws-s3-storage:
      bucket: npm
      endpoint: **redacted**
      accessKeyId: **redacted**
      secretAccessKey: **redacted**

  auth:
    groupnames:
      allowNonexistingLdapGroups: true
      ldapURL: **redacted**"
      bindDN: **redacted**
      bindPW: **redacted**
      groupDN: **redacted**
    ldap-done-right:
      cacheDuration: 300000
      ldapURL: **redacted**
      bindDN: **redacted**
      bindPW: **redacted**
      searchBase: **redacted**
      searchFilter: "(&(objectClass=npmuser)(enableNpmAccess=TRUE)(uid={{username}}))"
      groupBase: **redacted**
```

if you want to use this plugin without an ldap connection, you should disable `allowNonexistingLdapGroups` and populate groups manually
