### ISSUE TITLE
How to config a group?

### ISSUE THREAD

**Issue by hiyangguo** [deinstapel/verdaccio-groupnames#3]
How can I config a  group like this:
```
test-group:
    - tom
    - jerry
auth:
  groupnames: {}
  # Use other authentication plugins here.
packages:
  '@company/*:
    access: 'test-group'
    publish: 'test-group'
  '@*/*':
    access: '$group'
    publish: '$group'
    unpublish:
```
